### PR TITLE
Follow best Python practices

### LINKED ISSUE #2: Follow Python best practices for project structure
These include mainly:
- replace `install.sh` by `requirements.txt` for installing dependencies
- rename the `src` directory to `spef`
- use absolute imports everywhere (e.g. `from spef.modules.environment import Environment`)
- rename `__main__` from `main.py` to `main` (or something else)
- replace `run.sh` by a Python executable with `__main__` calling the function from the above point

### PR DESCRIPTION
**Pull request by viktormalik**
Features several improvements/changes:
- add license (Apache 2.0)
- add `pyproject.toml` containing:
  - basic information about the project
  - dependencies (moved from `install.sh`)
  - custom script `spef` for running the app, replacing `run.py`
  - setup of the custom style for Pygments (moved from `install.sh`)
- rename `src/` to `spef/` and use absolute imports everywhere (`import spef.x.y` instead of `import x.y`)
- removed the `__main__` function and replaced it with `__main__.py` - the app can now be started by executing the package as a module (`python -m spef`) or using the above `spef` script (after installation)
- add `MANIFEST.in` to include non-code files in the installation (configs, logs, etc.) - these should eventually be moved to better locations, ideally as a part of #7
- several changes in tests so that they are usable with the installed package

Also removed the custom user `test` from the container image as it didn't work well with Podman. This should be fixed in a proper way, eventually.

Resolves #2.

### CODE REVIEW

**Comment by viktormalik** [comment]
@ndizova you might want to have a look, especially if you're fine with adding the license.

**Review by JiriPavela — COMMENTED** [review]
Seems good to me! I have only one minor suggestion: I would consider updating the README file as well, so that it corresponds to the new setup process using pip install / pip editable install.

**Comment by viktormalik** [comment]
> Seems good to me! I have only one minor suggestion: I would consider updating the README file as well, so that it corresponds to the new setup process using pip install / pip editable install.

Right, that's the last item on my todo list that I forgot about 😀 Will add that, thanks!

**Review by JiriPavela — COMMENTED** [review]
The updated README seems fine now. I see no further issue that should block the PR merge.

**Review by JiriPavela — APPROVED** [review]

**Pull request merged**
